name: Deployment excercise 2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get-code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get-code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Test code
        run: npm run test  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get-code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build Code
        run: npm run build
      - name: Deploy the code
        run: echo "Deploying..."  